### ISSUE TITLE
Issue while taking snapshots from parking scenario

### ISSUE THREAD

**Issue by harish198829** [vignif/carla_parking#3]
First of all, Thank you for sharing this useful code. 

1. I want to take snapshots each frame of the whole scenario by surround cameras (left, right, front, rear).
2. Unfortunately, it is happening only to the last frame of the parking scenario. 
3. Could you through some light on how to get the intermediate frames, I feel like synchronization is not happened correctly.

**Comment by francescovigni** [comment]
Hi! thanks for your feedback!

To the best of my knowledge you should write a new script that captures periodically the camera streams you desire. 
Once the carla server is running you can connect to it with several clients and get information from available objects (i.e. cameras on a specific car).
In this way, you can also step through each frame without rewriting a function of this code.

Good luck!
